import mapInfo from "../../assets/maps/main.js";

export const mapWidth = mapInfo.width,
  mapHeight = mapInfo.height,
  tileSize = mapInfo.tileheight,
  tilesetColumns = mapInfo.tilesets[0].columns,
  layers = mapInfo.layers,
  canvasTileCount = 19,
  groundLayer = layers[0].data,
  blockingLayer = layers[1].data,
  entitiesLayer = layers[2].data,
  halfOfTileCount = Math.floor(canvasTileCount / 2),
  screenSize = canvasTileCount * tileSize,
  inventoryTabs = ["Items", "Weapons", "Clothes", "Fish"],
  gameCanvasX = 435,
  gameCanvasY = 13,
  gameCanvasSize = 1054,
  mapX = 1500,
  mapY = 0,
  mapSize = 420,
  W = 1920,
  H = 1080,
  classes = [
    "Mage",
    "Engineer",
    "Hunter",
    "Medic",
    "Fighter",
    "Assassin",
    "Dark mage",
    "Marksman",
    "Psycho"
  ],
  villages = [
    "Adraohr",
    "Jordakas",
    "Thodis",
    "Noranthar",
    "Lirffja",
    "Brrivami",
    "Lavelite",
    "Oghaarir",
    "Farathega"
  ],
  classDescriptions = [
    "Mages possess the power of control over the five elements, with that power they can deal high damage based on those. Can go either for high cast speed or quick burst damage. They have difficulties with traning stamina but their mana gains are much better.",
    "Engineers are not strong by themselves but they can create companions for themselves. Can go either for bomb specialists or robot overlord, who can call for support of either denfense bots, or offensive robots. They have high stamina but low cast speed.",
    "Hunters have lot's of stamina and strength, but low health. Beacuse of that, they have to be constanlty on the move, dodging the enemy attacks and take advantage of they long range weapons with great damage. Can go either for speed or stealth.",
    "Medics are good in close range battles and have high stamina and health. They possess the ability to heal themselves and allies. When comes to combat, they can go either for fighting style combined with weakening enemies or for devious style of traps and poisoning.",
    "Fighters are incredible fast and have lot's of stamina and health. Can go for either high damage focused on one enemy or crowd control effects. Either way when they come close to an enemy they are really deadly.",
    "Assassins are masters of shadows and can kill enemy before he even notice where the danger comes from. They are remarkably fast and hard to catch but their weakness is low health and stamina. Can go either for misdirection style or kill-run style.",
    "Dark mages sacrifice their health for other perks which makes them easy to kill when exposed to danger but they can deal damage from really long distance. Can go either for necromancy or curses.",
    "Marksmans can constatly deal high damage while moving and dashing. Their health is low but they are hard to catch. Can go eihter for defensive style - higher speed and quicker dashes or for offensive style - higher damage and damaging spells.",
    "Psychos have balanced stats and are good all-round. They are masters of illusion and tricks, constantly making their enemies uneasy and making sure that they can't anwser with a proper defense. Can go either for mind control spells or long range card attacks."
  ],
  villageDescriptions = [
    "Buffs: The element of earth is very strong here. Due to the sun magic, health is higher here and regenerate faster. All pure magic, focused on helping others by healing and buffing is stronger. \n De-buffs: All technology work backwards here. Also all lose some of their strenght and their attacks seem to couse less harm.",
    "Jordakas",
    "Thodis",
    "Noranthar",
    "Lirffja",
    "Brrivami",
    "Lavelite",
    "Oghaarir",
    "Farathega"
  ];
